# Cloud Run deployment configuration for Frontend
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gsf-web-frontend
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 60
      containers:
      - image: gcr.io/YOUR_PROJECT_ID/gsf-web-frontend:latest
        ports:
        - name: http1
          containerPort: 80
        env:
        - name: VITE_API_BASE_URL
          value: "https://YOUR_BACKEND_URL/api"
        resources:
          limits:
            cpu: "1"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"

