# Cloud Build configuration for automated builds
steps:
  # Build backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gsf-web-backend', './backend']
    id: 'build-backend'

  # Build frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gsf-web-frontend', './frontend']
    id: 'build-frontend'

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gsf-web-backend']
    waitFor: ['build-backend']
    id: 'push-backend'

  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gsf-web-frontend']
    waitFor: ['build-frontend']
    id: 'push-frontend'

  # Deploy backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'gsf-web-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/gsf-web-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    waitFor: ['push-backend']
    id: 'deploy-backend'

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'gsf-web-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/gsf-web-frontend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    waitFor: ['push-frontend']
    id: 'deploy-frontend'

images:
  - 'gcr.io/$PROJECT_ID/gsf-web-backend'
  - 'gcr.io/$PROJECT_ID/gsf-web-frontend'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

