# Cloud Run deployment configuration for Backend
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gsf-web-backend
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/YOUR_PROJECT_ID/gsf-web-backend:latest
        ports:
        - name: http1
          containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: mysql-host
              key: host
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-user
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: password
        - name: MYSQL_DATABASE
          value: "gsf_web"
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"

